#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

go-back:
    path: /back
    controller: App\Controller\HomeController::goBack

category:
    path: /categoria/{slug?}
    controller: App\Controller\CategoryController::category

product:
    path: /producto/{slug?}
    controller: App\Controller\ProductController::product

product-search:
    path: /busqueda/
    controller: App\Controller\ProductController::productSearch

ajax-register:
    path: /ajaxregister
    controller: App\Controller\AjaxController::registerUser

ajax-login-error:
    path: /ajaxloginError
    controller: App\Controller\AjaxController::logUserError

ajax-login-success:
    path: /ajaxloginSuccess
    controller: App\Controller\AjaxController::logUserSuccess

ajax-logout:
    path: /ajaxlogout
    controller: App\Controller\AjaxController::logout

not-found:
    path: /error
    controller: App\Controller\HomeController::notFound

login:
    path: /login
    controller: App\Controller\UserController::login

login-success:
    path: /loginSuccess
    controller: App\Controller\HomeController::loginSuccess

back-to-index:
    path: /backtoindex
    controller: App\Controller\HomeController::backToIndex

pre-logout:
    path: /prelogout
    controller: App\Controller\HomeController::preLogout

logout:
    path: /logout



########################################################
######################## ADMIN #########################
########################################################

admin:
    path: /admin
    controller: App\Controller\AdminController::index

admin-users:
    path: /admin/usuarios
    controller: App\Controller\AdminController::users

admin-products:
    path: /admin/productos
    controller: App\Controller\AdminController::products

admin-reviews:
    path: /admin/opiniones
    controller: App\Controller\AdminController::reviews

admin-orders:
    path: /admin/ordenes
    controller: App\Controller\AdminController::orders

admin-messages:
    path: /admin/mensajes
    controller: App\Controller\AdminController::messages

admin-categories:
    path: /admin/categorias
    controller: App\Controller\AdminController::categories

#######################################################

active-user:
    path: /admin/active-user/{id?}
    controller: App\Controller\AdminController::activeUser

active-product:
    path: /admin/active-product/{id?}
    controller: App\Controller\AdminController::activeProduct

active-review:
    path: /admin/active-review/{id?}
    controller: App\Controller\AdminController::banReview

active-order:
    path: /admin/active-order/{id?}
    controller: App\Controller\AdminController::activeOrder
