#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

category:
    path: /categoria/{slug?}
    controller: App\Controller\CategoryController::category
    defaults:
      categoria: Ropa

product:
    path: /producto/{slug?}
    controller: App\Controller\ProductController::product

product-search:
    path: /busqueda/
    controller: App\Controller\ProductController::productSearch

ajax-register:
    path: /ajaxregister
    controller: App\Controller\AjaxController::registerUser

ajax-login:
    path: /ajaxlogin
    controller: App\Controller\AjaxController::logUser

not-found:
    path: /error
    controller: App\Controller\HomeController::notFound

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout

########################################################
######################## ADMIN #########################
########################################################

admin:
    path: /admin
    controller: App\Controller\AdminController::index

admin-users:
    path: /admin/usuarios
    controller: App\Controller\AdminController::index

admin-products:
    path: /admin/productos
    controller: App\Controller\AdminController::index

admin-reviews:
    path: /admin/opiniones
    controller: App\Controller\AdminController::index

admin-orders:
    path: /admin/ordenes
    controller: App\Controller\AdminController::index

admin-messages:
    path: /admin/mensajes
    controller: App\Controller\AdminController::index

admin-categories:
    path: /admin/categorias
    controller: App\Controller\AdminController::index
