#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

go-back:
    path: /back
    controller: App\Controller\HomeController::goBack

ajax-register:
    path: /ajaxregister
    controller: App\Controller\AjaxController::registerUser

ajax-login-error:
    path: /ajaxloginError
    controller: App\Controller\AjaxController::logUserError

ajax-login-success:
    path: /ajaxloginSuccess
    controller: App\Controller\AjaxController::logUserSuccess

ajax-logout:
    path: /ajaxlogout
    controller: App\Controller\AjaxController::logout

not-found:
    path: /error
    controller: App\Controller\HomeController::notFound

login:
    path: /login
    controller: App\Controller\UserController::login

login-success:
    path: /loginSuccess
    controller: App\Controller\HomeController::loginSuccess

back-to-index:
    path: /backtoindex
    controller: App\Controller\HomeController::backToIndex

pre-logout:
    path: /prelogout
    controller: App\Controller\HomeController::preLogout

logout:
    path: /logout

########################################################
######################## PRODUCTOS #####################
########################################################

category:
    path: /categoria/{slug?}
    controller: App\Controller\CategoryController::category

product:
    path: /producto/{slug?}
    controller: App\Controller\ProductController::product

product-search:
    path: /busqueda/
    controller: App\Controller\ProductController::productSearch

########################################################
######################## CESTA #########################
########################################################

cesta:
    path: /cesta/{slug?}
    controller: App\Controller\OrderController::addToOrder

cesta-agregar:
    path: /cesta/agregar/
    controller: App\Controller\OrderController::addToOrder

########################################################
######################## CONTACTO ######################
########################################################

contactform:
    path: /contacto
    controller: App\Controller\HomeController::sendForm


########################################################
######################## ADMIN #########################
########################################################

admin:
    path: /admin
    controller: App\Controller\AdminController::index

admin-users:
    path: /admin/usuarios
    controller: App\Controller\AdminController::users

admin-products:
    path: /admin/productos
    controller: App\Controller\AdminController::products

admin-reviews:
    path: /admin/opiniones
    controller: App\Controller\AdminController::reviews

admin-orders:
    path: /admin/ordenes
    controller: App\Controller\AdminController::orders

admin-messages:
    path: /admin/mensajes
    controller: App\Controller\AdminController::messages

admin-categories:
    path: /admin/categorias
    controller: App\Controller\AdminController::categories

#######################################################

active-user:
    path: /admin/active-user/{id?}
    controller: App\Controller\AdminController::activeUser

active-product:
    path: /admin/active-product/{id?}
    controller: App\Controller\AdminController::activeProduct

active-review:
    path: /admin/active-review/{id?}
    controller: App\Controller\AdminController::banReview

delete-user:
    path: /admin/delete-user/{id?}
    controller: App\Controller\AdminController::deleteUser

delete-product:
    path: /admin/delete-product/{id?}
    controller: App\Controller\AdminController::deleteProduct

delete-item:
    path: /admin/delete-product/{product?}/{order?}
    controller: App\Controller\AdminController::deleteOrderItem

delete-message:
    path: /admin/delete-message/{id?}
    controller: App\Controller\AdminController::deleteMessage

delete-category:
    path: /admin/delete-category/{id?}
    controller: App\Controller\AdminController::deleteCategory

#######################################################

show-message:
    path: /admin/mensajes/msg/{id?}
    controller: App\Controller\AdminController::showMessage

edit-user:
    path: /admin/usuarios/usr/{id?}
    controller: App\Controller\AdminController::editUser

edit-product:
    path: /admin/productos/pd/{id?}
    controller: App\Controller\AdminController::editProduct

show-review:
    path: /admin/opiniones/rw/{id?}
    controller: App\Controller\AdminController::showReview

edit-order:
    path: /admin/ordenes/od/{id?}
    controller: App\Controller\AdminController::editOrder

edit-category:
    path: /admin/categorias/catr/{id?}
    controller: App\Controller\AdminController::editCategory

#############################################################

create-user:
    path: /admin/usuarios/nuevo
    controller: App\Controller\AdminController::createUser

create-product:
    path: /admin/productos/nuevo/{id?}
    controller: App\Controller\AdminController::createProduct

create-category:
    path: /admin/categorias/nueva
    controller: App\Controller\AdminController::createCategory
