#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

category:
    path: /categoria/{slug?}
    controller: App\Controller\CategoryController::category
    defaults:
      categoria: Ropa

ajax-register:
    path: /ajaxregister
    controller: App\Controller\AjaxController::registerUser

ajax-login:
    path: /ajaxlogin
    controller: App\Controller\AjaxController::logUser

not-found:
    path: /error
    controller: App\Controller\HomeController::notFound
